AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ghl-chat

Resources:
  # WebhooksApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: $default

  WebhooksLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cicd_ghl_webhooks
      Handler: ghl_chat_history_lambda.lambda_handler
      Runtime: python3.11
      CodeUri: src
      Timeout: 300
      Events:
        WebhooksApi:
          Type: Api
          Properties:
            Path: /cicd_ghl_webhook
            Method: ANY

  ReplyLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cicd_ghl_reply
      Handler: ghl_reply_lambda.lambda_handler
      Runtime: python3.11
      CodeUri: src
      Timeout: 300
      Events:
        WebhooksLambdaEvent:
          Type: Lambda
          Properties:
            FunctionName: !Ref WebhooksLambda

  WebhooksLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WebhooksLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource: '*'
  ReplyLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ReplyLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource: '*'
    
  

  # OifBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: ownitfit-silvhua

  # SessionTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: SessionTable
  #     AttributeDefinitions:
  #       - AttributeName: SessionId
  #         AttributeType: S
  #       - AttributeName: type  
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: SessionId
  #         KeyType: HASH
  #       - AttributeName: type  
  #         KeyType: RANGE
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebhooksApi:
    Description: "API Gateway endpoint URL for WebhooksLambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cicd_ghl_webhook/"
  WebhooksLambdFunction:
    Description: "WebhooksLambda ARN"
    Value: !GetAtt WebhooksLambda.Arn
  ReplyLambdaFunction:
    Description: "ReplyLambda ARN"
    Value: !GetAtt ReplyLambda.Arn
  WebhooksLambdaIamRole:
    Description: "Implicit IAM Role created for WebhooksLambda"
    Value: !GetAtt WebhooksLambdaRole.Arn
  ReplyLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for ReplyLambda"
    Value: !GetAtt ReplyLambdaFunctionRole.Arn