AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ghl-chat

Resources:
  # WebhooksApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: $default

  ReplyLambda:
    # Type: AWS::Lambda::Function
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ghl_reply
      Handler: ghl_reply_lambda.lambda_handler
      Role: arn:aws:iam::661497771663:role/service-role/ghl_reply-role-xi672gxy
      Runtime: python3.11
      CodeUri: src

  WebhooksLambda:
    # Type: AWS::Lambda::Function
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ghl_webhooks
      Handler: ghl_chat_history_lambda.lambda_handler
      Role: arn:aws:iam::661497771663:role/service-role/ghl_webhooks-role-7acnstq7
      Runtime: python3.11
      CodeUri: src
      Timeout: 300
      # Events:
      #   WebhooksApi:
      #     Type: Api
      #     Properties:
      #       Path: /ghl_webhook
      #       Method: ANY

  # OifBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: ownitfit-silvhua

  # SessionTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: SessionTable
  #     AttributeDefinitions:
  #       - AttributeName: SessionId
  #         AttributeType: S
  #       - AttributeName: type  
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: SessionId
  #         KeyType: HASH
  #       - AttributeName: type  
  #         KeyType: RANGE
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1