version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "silvhua"
github_repo = "GHL-chat"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-wZa9f5hPeZFb"
cloudformation_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-9UZKUY9snq2H"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-fepziccg4nk6"
image_repository = ""
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-a5LtoOmGFKRW"
cloudformation_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-o3fbfPikXO6j"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ecopdm998jna"
image_repository = ""
region = "us-west-2"
