version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "silvhua"
github_repo = "GHL-chat"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-IBQpv0Zm6IX3"
cloudformation_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-6M7nwbhM9yIA"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-ld2eyroophf0"
image_repository = ""
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-onD90D3FDGwl"
cloudformation_execution_role = "arn:aws:iam::661497771663:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-EKqVW3juq2Co"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-frz5xdkafqxk"
image_repository = ""
region = "us-west-2"
